version: 1.0.{build}
branches:
  only:
    - master
skip_commits:
 files:
   - docs/*
   - '**/*.html'
skip_branch_with_pr: true
max_jobs: 1
image: Visual Studio 2015
init:
  - git config --global core.autocrlf input
shallow_clone: true
environment:
  matrix:
    - PYTHON_VERSION: "3.5"
      MINICONDA: "C:\\Miniconda35-x64"
    - PYTHON_VERSION: "3.6"
      MINICONDA: "C:\\Miniconda36-x64"
matrix:
  fast_finish: true
install:
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - conda activate
  - conda config --set always_yes True
  - conda config --add channels jrmadsen
  - conda config --add channels conda-forge
  - conda update conda  # required in order to find mkl-devel
  - >
      conda install python=%PYTHON_VERSION%
      --file envs/requirements-all.txt
      --file envs/requirements-win-build.txt
  # Check that we have the expected version and architecture for Python
  - conda info -a
  - "python --version"
  # - where gcc
platform: x64
configuration: Debug
build_script:
  - set CC=gcc
  - python setup.py install
before_test:
  - cd test/
test_script:
  - nosetests -v
